# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a4465b10a57e638f03a09c0aaf62d8d7ae92b690d63efb9f3c1e609c9123ea881928c26b3d3929ddf295d56df9df60542cd67ce4260abb8be714ca5c8b9102a

test:
  secret_key_base: 2505053d78df94cdcfb3e9f9c1f1e26cb8ec44e24e9600823b556414f8a95bc5cdc5204950e07a55ca3f8536473ab31002929d3d373a4cd0668de1cecc6bad2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
